version: "{build}"

os: Windows Server 2012

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

clone_folder: c:\projects\CustomActionFastMsi
